StartingGun: M1911
Guns:
  Pistols:
    B23R:
      Ammo: 15/105
      Damage: 3
      FireRate: 
      PackAPunch:
        Damage: 15
        Name: B34R
        Ammo: 20/180
    Executioner:
      Ammo: 5/75
      Damage: 23
      PackAPunch:
        Damage: 40
        Name: Voice of Justice
        Ammo: 5/100
    Five-Seven:
      Ammo: 20/120
      Damage: 3
      PackAPunch:
        Damage: 15
        Name: Ultra
        Ammo: 20/200
    Kap-40:
      Ammo: 12/96
      Damage: 3
      PackAPunch:
        Damage: 12
        Name: Karmic Atom Perforator-4000
        Ammo: 15/180
    M1911:
      Ammo: 8/80
      Damage: 2
      PackAPunch:
        Damage: 30
        Name: C-3000 b1at-ch35
        Ammo: 6/40
    Python:
      Ammo: 6/84
      Damage: 30
      PackAPunch:
        Damage: 50
        Name: Cobra
        Ammo: 12/96
        

  Shotguns:
    M1216:
      Ammo: 16/84
      Damage: 30
      PackAPunch:
        Damage: 40
        Name: Mesmerizer
        Ammo: 24/72
    Olympia:
      Ammo: 2/38
      Damage: 20
      PackAPunch:
        Damage: 30
        Name: Hades
        Ammo: 2/60
    R870 MCS:
      Ammo: 6/48
      Damage: 22
      PackAPunch:
        Damage: 30
        Name: Refitted-870 Mechanical Cranium Sequencer
        Ammo: 10/70
    S12:
      Ammo: 10/30
      Damage: 24
      PackAPunch:
        Damage: 30
        Name: Synthetic Dozen
        Ammo: 10/50

  AssaultRifles:
    AN-94:
      Ammo: 30/90
      Damage: 5
      PackAPunch:
        Damage: 10 
        Name: Actuated Neutralizer 94000
        Ammo: 50/600
    Colt M16A1:
      Ammo: 30/120
      Damage: 4
      PackAPunch:
        Damage: 13
        Name: Skullcrusher
        Ammo: 30/270
    FAL:
      Ammo: 20/180
      Damage: 7
      PackAPunch:
        Damage: 15 
        Name: EPC WN
        Ammo: 30/360
    M8A1:
      Ammo: 32/192
      Damage: 3
      PackAPunch:
        Damage: 7 
        Name: Micro Aerator
        Ammo: 42/336
    M14:
      Ammo: 8/96
      Damage: 4
      PackAPunch:
        Damage: 7
        Name: Mnesia
        Ammo: 16/192
    M27:
      Ammo: 30/240
      Damage: 5
      PackAPunch:
        Damage: 10
        Name: Mystifier
        Ammo: 30/360
    MTAR:
      Ammo: 30/240
      Damage: 5
      PackAPunch:
        Damage: 10
        Name: Malevolent Taxonomic Anodized Redeemer
        Ammo: 30/360
    SMR:
      Ammo: 20/140
      Damage: 3
      PackAPunch:
        Damage: 8 
        Name: SM1L3R
        Ammo: 30/390
    Type 25:
      Ammo: 30/150
      Damage: 4
      PackAPunch:
        Damage: 12
        Name: Strain 25
        Ammo: 30/270
    
  LightMachineGuns:
    HAMR:
      Ammo: 135/375
      Damage: 10
      PackAPunch:
        Damage: 15
        Name: SLDG-HAMR
        Ammo: 125/625
    LSAT:
      Ammo: 100/400
      Damage: 12
      PackAPunch:
        Damage: 16
        Name: FSIRT
        Ammo: 100/600
    RPD:
      Ammo: 100/400
      Damage: 10
      PackAPunch:
        Damage: 15
        Name: Relativistic Punishment Device
        Ammo: 125/750


  SubMachineGuns:
    Chicom CQB:
      Ammo: 40/120
      Damage: 2
      PackAPunch:
        Damage: 7
        Name: Chicom Cataclysmic Quadruple Burst
        Ammo: 40/200
    MP5:
      Ammo: 30/120
      Damage: 3
      PackAPunch:
        Damage: 7
        Name: MP115 Kollider
        Ammo: 40/200
    PDW-57:
      Ammo: 50/200
      Damage: 2
      PackAPunch:
        Damage: 6 
        Name: Predictive Death Wish 57000
        Ammo: 50/350

  SniperRifles:
    Barret M82A1:
      Ammo: 5/30
      Damage: 50
      PackAPunch:
        Damage: 70
        Name: Macro Annihilator
        Ammo: 7/42
    DSR 50:
      Ammo: 4/48
      Damage: 50
      PackAPunch:
        Damage: 70
        Name: Dead Specimen Reactor 5000
        Ammo: 8/96
    SVU-AS:
      Ammo: 12/48
      Damage: 30
      PackAPunch:
        Damage: 50
        Name: Shadowy Veil Utilizer
        Ammo: 12/192
  Others:
    Ray Gun:
      Ammo: 20/160
      Damage: 90
      PackAPunch:
        Damage: 120 
        Name: Porter's X2 Ray Gun
        Ammo: 40/200